/* Scanned course handout Tema: fremtid, expanded into a self-study unit. */
window.FREMTID_TOPIC = {
  id: "fremtid", title: "Fremtid · 未来", level: "A2–B1", icon: "🚀",
  intro: "学会表达计划、意愿、预测和结果；把语法放进目标、家庭、工作与旅行的真实语境。",
  grammar: [
    { title: "现在时 + 未来时间", cue: "安排明确、时间表清楚", form: "现在时 + 未来时间词", example: "Jeg leser ei bok på søndag.", zh: "我星期天读一本书。", note: "挪威语常用现在时表达已经安排好的未来事项，特别是有明确时间词时。上下文必须能看出是未来。出行也常用现在时：Vi drar til Oslo neste uke（我们下周去奥斯陆）。" },
    { title: "skal · 计划与承诺", cue: "已有安排、决定或责任", form: "skal + 动词原形（不加 å）", example: "Jeg skal rydde rommet i morgen.", zh: "我明天要收拾房间。", note: "skal 强调说话人已有计划、安排或承诺。主语变化时 skal 不变，后面的动词保持原形：Vi skal besøke bestemor til helgen.（我们周末要去看奶奶。）" },
    { title: "kommer til å · 预测", cue: "根据迹象或判断预测结果", form: "kommer til å + 动词原形", example: "Det kommer til å regne i kveld.", zh: "今晚会下雨。", note: "常用于预测或认为某事很可能发生。注意结构中 til 后必须有 å：kommer til å regne。看到乌云时，这个表达尤其自然。" },
    { title: "vil · 愿望与意愿", cue: "想做、希望做、愿意做", form: "vil + 动词原形（不加 å）", example: "Jeg vil lære å danse.", zh: "我想学跳舞。", note: "vil 表达个人意愿、希望或选择；后面的动作仍用原形。lære å danse 中，å 属于 lære å danse 这个“学习做某事”的结构。" },
    { title: "blir · 结果与变化", cue: "描述未来会形成的状态或结果", form: "blir + 名词/形容词；或 blir + ferdig", example: "Det blir gøy å feire nyttår.", zh: "庆祝新年会很有趣。", note: "blir 是 bli 的现在时，可表示“将会变得/会是”。也可说 Vi blir ferdige med prosjektet neste uke（我们下周会完成项目）。单独的 blir 不等于英语 will + 动词原形。" },
    { title: "把五种表达放在一起比较", cue: "同一件事，不同语气", form: "时间表 / 计划 / 预测 / 愿望 / 结果", example: "Jeg lærer norsk neste år. / Jeg skal lære norsk. / Jeg kommer til å lære norsk. / Jeg vil lære norsk. / Det blir lettere.", zh: "我明年学挪威语。/ 我计划学挪威语。/ 我会学会挪威语（预测）。/ 我想学挪威语。/ 这会变得更容易。", note: "选择时先问自己：这是排好的日程吗？是我的计划吗？是预测吗？是愿望吗？还是在说结果/状态？不要把所有未来都机械地翻译成 will。" },
    { title: "主句 V2 语序", cue: "时间放句首时，变位动词仍在第二位", form: "I morgen + skal + jeg + rydde …", example: "I morgen skal jeg rydde rommet.", zh: "明天我会收拾房间。", note: "时间成分 I morgen 占主句第一位，变位动词 skal 必须紧跟其后，再放主语 jeg。不能说 I morgen jeg skal …。" },
    { title: "不规则动词与时态回顾", cue: "先找助动/情态动词，再看后面动词", form: "å ville–vil–ville–har villet · å skulle–skal–skulle–har skullet · å bli–blir–ble–har blitt", example: "Jeg vil spare mer. / Jeg sparte mer i fjor. / Jeg har spart mye.", zh: "我想多存钱。/ 去年我多存了钱。/ 我已经存了很多。", note: "情态动词 vil/skal 后用原形；过去的计划可用 skulle；描述已发生的过去用过去时；har 后要用完成分词。未来语境不等于每个动词都要加未来助动词。" }
  ],
  vocabulary: [
    ["et nyttår", "新年；岁末年初/新年时段", "名词", "et nyttår – nyttåret – nyttår – nyttårene", "Vi skal feire nyttår med familien.", "我们要和家人一起庆祝新年。", "🎆"],
    ["et mål", "目标", "名词", "et mål – målet – mål – målene", "Målet mitt er å snakke bedre norsk.", "我的目标是把挪威语说得更好。", "🎯"],
    ["en drøm", "梦想", "名词", "en drøm – drømmen – drømmer – drømmene", "Drømmen hennes er å bo nær fjellet.", "她的梦想是住在山附近。", "💭"],
    ["en plan", "计划；方案；打算/意图（依语境）", "名词", "en plan – planen – planer – planene", "Vi har en plan for neste år.", "我们对明年有一个计划。", "🗓️"],
    ["en mulighet", "机会；可能性", "名词", "en mulighet – muligheten – muligheter – mulighetene", "Kanskje får jeg en ny mulighet på jobben.", "也许我会在工作中获得一个新机会。", "🚪"],
    ["en utfordring", "挑战", "名词", "en utfordring – utfordringen – utfordringer – utfordringene", "Det kan bli en spennende utfordring.", "这可能会成为一个令人兴奋的挑战。", "🧩"],
    ["en løsning", "解决办法；解决方案；（化学）溶液", "名词", "en løsning – løsningen – løsninger – løsningene", "Vi skal finne en god løsning.", "我们会找到一个好办法。", "💡"],
    ["en suksess", "成功；顺利的结果", "名词", "en suksess – suksessen – suksesser – suksessene", "Små steg kan føre til suksess.", "小小的进步也能带来成功。", "🏆"],
    ["ei helse", "健康", "名词", "ei helse – helsa", "Jeg skal gå tur for helsa.", "我打算散步来保持健康。", "💚"],
    ["ei trening", "锻炼；训练", "名词", "ei trening – treninga – treninger – treningene", "Jeg skal trene tre ganger i uka.", "我计划每周锻炼三次。", "🏃"],
    ["en endring", "变化；改变（可指变化过程或变化后的结果）", "名词", "en endring – endringen – endringer – endringene", "Jeg vil gjøre noen endringer.", "我想做一些改变。", "🔄"],
    ["en motivasjon", "行动意愿；动力（做某事的意愿）", "名词", "en motivasjon – motivasjonen – motivasjoner – motivasjonene", "Familien gir meg motivasjon.", "家人给我动力。", "🔥"],
    ["en innsats", "努力；投入；贡献（依语境）", "名词", "en innsats – innsatsen – innsatser – innsatsene", "Med jevn innsats lærer jeg mer.", "持续努力，我就能学得更多。", "💪"],
    ["en glede", "喜悦；快乐；令人高兴的事（依语境）", "名词", "en glede – gleden – gleder – gledene", "Det blir en glede å møte familien.", "见到家人会是一件开心的事。", "😊"],
    ["en rutine", "日常习惯；固定程序；熟练经验（依语境）", "名词", "en rutine – rutinen – rutiner – rutinene", "Jeg skal lage en ny rutine.", "我打算建立一个新的日常习惯。", "🔁"],
    ["et håp", "希望；盼望；有望实现的好结果", "名词", "et håp – håpet – håp – håpene", "Jeg håper at det blir fint vær.", "我希望天气会很好。", "🌤️"],
    ["en utvikling", "发展；变化过程；（论述）展开/说明（依语境）", "名词", "en/ei utvikling – utviklingen/utviklinga – utviklinger – utviklingene", "Jeg ser en positiv utvikling.", "我看到了积极的发展趋势。", "📈"],
    ["en beslutning", "决定；决议（作出判断或决定这一行为/结果）", "名词", "en beslutning – beslutningen – beslutninger – beslutningene", "Hun skal ta en viktig beslutning.", "她要做一个重要决定。", "✅"],
    ["et forsett", "打算；意图；决心（新年计划常见于 nyttårsforsett）", "名词", "et forsett – forsettet – forsetter – forsettene", "Nyttårsforsettet mitt er å lese mer.", "我的新年计划是多读书。", "📝"],
    ["en framtid", "未来；前景（指将来的处境或发展可能）", "名词", "en framtid – framtiden – framtider – framtidene", "Vi snakker om framtiden.", "我们在谈论未来。", "🔮"],
    ["en forbedring", "改善；改进；进步（相较之前变得更好）", "名词", "en forbedring – forbedringen – forbedringer – forbedringene", "Jeg merker en forbedring i norsken min.", "我感觉自己的挪威语有了进步。", "📊"],
    ["en aktivitet", "活动；活跃状态（看语境）", "名词", "en aktivitet – aktiviteten – aktiviteter – aktivitetene", "Vi skal velge en aktivitet for helgen.", "我们要为周末选一项活动。", "⚽"],
    ["et valg", "选择；（政治）选举/投票", "名词", "et valg – valget – valg – valgene", "Det er et viktig valg.", "这是一个重要的选择。", "🔀"],
    ["en opplevelse", "亲身经历；体验；经历的事情", "名词", "en opplevelse – opplevelsen – opplevelser – opplevelsene", "Reisen blir en fin opplevelse.", "这次旅行会是一次美好的体验。", "🎡"],
    ["ei reise", "一次旅行；旅程（名词；动词 å reise 表示旅行/出行）", "名词", "en/ei reise – reisen/reisa – reiser – reisene", "Jeg skal planlegge ei reise.", "我打算计划一次旅行。", "🧳"],
    ["en karriere", "职业生涯；职业发展（马术语境另有“疾驰”义）", "名词", "en karriere – karrieren – karrierer – karrierene", "Hun vil starte en ny karriere.", "她想开启一段新的职业生涯。", "👩‍💻"],
    ["en familie", "家庭；家人", "名词", "en familie – familien – familier – familiene", "Jeg vil reise med familien.", "我想和家人一起旅行。", "👨‍👩‍👦"],
    ["et vennskap", "友谊；朋友间的良好关系", "名词", "et vennskap – vennskapet – vennskap – vennskapene", "Et godt vennskap betyr mye.", "一段美好的友谊很重要。", "🫶"],
    ["en framgang", "进展；进步（朝更好的方向发展）", "名词", "en framgang – framgangen – framganger – framgangene", "Jeg har hatt god framgang.", "我进步很大。", "🌿"],
    ["å ville", "想；愿意", "动词", "vil – ville – har villet", "Jeg vil lære et nytt språk.", "我想学一门新语言。", "🗣️"],
    ["å skulle", "将要；计划；本应", "动词", "skal – skulle – har skullet", "Vi skal besøke familien i helgen.", "我们周末要去看家人。", "📌"],
    ["å komme til å", "将会；预计会（表达预测；另有“碰巧/得以”义）", "动词结构", "kommer til å – kom til å – har kommet til å", "Det kommer til å regne i kveld.", "今晚会下雨。", "🌧️"],
    ["å bli", "变成；将会是", "动词", "blir – ble – har blitt", "Det blir lettere med øvelse.", "练习会让事情变得更容易。", "🌱"],
    ["å planlegge", "计划", "动词", "planlegger – planla – har planlagt", "Jeg planlegger en reise.", "我在计划一次旅行。", "🧭"],
    ["å håpe", "希望", "动词", "håper – håpet – har håpet", "Jeg håper å få mer tid.", "我希望能有更多时间。", "🤞"],
    ["å drømme", "做梦；梦想", "动词", "drømmer – drømte – har drømt", "Han drømmer om en ny jobb.", "他梦想着一份新工作。", "✨"],
    ["å forbedre", "改善；提高", "动词", "forbedrer – forbedret – har forbedret", "Jeg vil forbedre norsken min.", "我想提高自己的挪威语。", "⬆️"],
    ["å tenke", "想；思考", "动词", "tenker – tenkte – har tenkt", "Jeg tenker på framtida.", "我在思考未来。", "🤔"],
    ["å ønske", "希望；想要", "动词", "ønsker – ønsket – har ønsket", "Jeg ønsker meg en ny jobb.", "我希望找到一份新工作。", "🌠"],
    ["å starte", "开始；启动", "动词", "starter – startet – har startet", "Jeg skal starte et nytt prosjekt.", "我准备开始一个新项目。", "▶️"],
    ["å trene", "锻炼；训练；训练/执教某人（依结构）", "动词", "trener – trente – har trent", "Jeg skal trene tre ganger i uka.", "我每周要锻炼三次。", "🏃‍♀️"],
    ["å lære", "学习；学会", "动词", "lærer – lærte – har lært", "Jeg vil lære et nytt språk.", "我想学一门新语言。", "📚"],
    ["å oppnå", "达到；实现", "动词", "oppnår – oppnådde – har oppnådd", "Jeg håper å oppnå målet mitt.", "我希望实现自己的目标。", "🏁"],
    ["å prøve", "尝试；努力", "动词", "prøver – prøvde – har prøvd", "Jeg skal prøve å spise sunnere.", "我会试着吃得更健康。", "🧪"],
    ["å spare", "存钱；节省", "动词", "sparer – sparte – har spart", "Jeg vil spare mer penger.", "我想多存一些钱。", "🐷"],
    ["å jobbe", "工作", "动词", "jobber – jobbet – har jobbet", "Jeg skal jobbe mindre neste år.", "我明年会少工作一些。", "💼"],
    ["å reise", "旅行；出行", "动词", "reiser – reiste – har reist", "Vi skal reise til et nytt land.", "我们要去一个新的国家旅行。", "✈️"],
    ["å spise", "吃；用餐；（引申）耗掉、占去（依语境）", "动词", "spiser – spiste – har spist", "Jeg vil spise sunnere.", "我想吃得更健康。", "🥗"],
    ["å gjøre", "做；进行", "动词", "gjør – gjorde – har gjort", "Jeg skal gjøre noen endringer.", "我打算做一些改变。", "🛠️"],
    ["å fokusere", "专注；集中注意力", "动词", "fokuserer – fokuserte – har fokusert", "Jeg skal fokusere mer på norsk.", "我会更专注于挪威语。", "🔎"],
    ["å prioritere", "优先考虑；优先处理；按优先级排列", "动词", "prioriterer – prioriterte – har prioritert", "Jeg vil prioritere helsa mi.", "我想把健康放在优先位置。", "📌"],
    ["å skape", "创造；产生；造成（依语境）", "动词", "skaper – skapte – har skapt", "Vi kan skape en god rutine.", "我们可以建立一个好习惯。", "🎨"],
    ["å forandre", "改变；使变化", "动词", "forandrer – forandret – har forandret", "Små steg kan forandre hverdagen.", "一点点行动也能改变日常生活。", "🦋"],
    ["å oppdage", "发现；察觉/注意到；（首次）发现某地或现象", "动词", "oppdager – oppdaget – har oppdaget", "Jeg kommer til å oppdage nye steder.", "我会发现一些新地方。", "🔭"],
    ["å glede seg", "期待；因……感到高兴（分别用 glede seg til / over）", "动词短语", "gleder seg – gledet seg – har gledet seg", "Jeg gleder meg til reisen.", "我很期待这次旅行。", "🎉"],
    ["å fullføre", "完成；做完（把课程、任务等进行到底）", "动词", "fullfører – fullførte – har fullført", "Jeg skal fullføre kurset.", "我准备完成这门课程。", "🏅"],
    ["å se for seg", "想象；设想（在脑中形成画面或情景）", "动词短语", "ser for seg – så for seg – har sett for seg", "Jeg ser for meg en roligere hverdag.", "我想象一种更平静的日常生活。", "🪄"],
    ["frisk", "健康的；清新的", "形容词", "friskere – friskest", "Jeg vil bli friskere.", "我想变得更健康。", "🍃"],
    ["flink", "擅长的；能干的", "形容词", "flinkere – flinkest", "Hun blir flinkere til å snakke norsk.", "她会越来越擅长说挪威语。", "🌟"],
    ["god", "好的；擅长的", "形容词", "bedre – best（不规则）", "Det blir bedre neste år.", "明年会更好。", "👍"],
    ["sterk", "强壮的；强有力的", "形容词", "sterkere – sterkest", "Trening gjør kroppen sterkere.", "锻炼让身体更强壮。", "🏋️"],
    ["motivert", "有动力的；对……有积极性的（常用 motivert for）", "形容词", "mer motivert – mest motivert", "Jeg føler meg mer motivert nå.", "我现在感觉更有动力了。", "⚡"],
    ["glad", "高兴的", "形容词", "gladere – gladest", "Barna blir glade når vi reiser.", "我们旅行时孩子们会很开心。", "😄"],
    ["aktiv", "积极的；活跃的", "形容词", "mer aktiv – mest aktiv", "Jeg skal være mer aktiv.", "我会更积极一些。", "🚴"],
    ["energisk", "精力充沛的；干劲十足的", "形容词", "mer energisk – mest energisk", "En god rutine gjør meg mer energisk.", "良好的习惯让我更有精力。", "🔋"],
    ["fokusert", "专注的；注意力集中的（常用 fokusert på）", "形容词", "mer fokusert – mest fokusert", "Jeg vil være mer fokusert på norsk.", "我想更专注于挪威语。", "🎧"],
    ["lykkelig", "幸福的", "形容词", "lykkeligere – lykkeligst", "Jeg blir lykkelig av tid med familien.", "和家人在一起让我幸福。", "🏡"],
    ["rolig", "平静的；安静的；从容的（依语境）", "形容词", "roligere – roligst", "Det blir roligere etter ferien.", "假期后会安静一些。", "🌊"],
    ["sunn", "健康的；有益健康的；明智/稳健的（依语境）", "形容词", "sunnere – sunnest", "Jeg vil spise sunnere.", "我想吃得更健康。", "🥦"],
    ["positiv", "积极的；正面的；（检测结果）阳性的（依语境）", "形容词", "mer positiv – mest positiv", "Jeg prøver å være mer positiv.", "我努力让自己更积极。", "☀️"],
    ["kreativ", "有创意的；善于产生并实现新想法的", "形容词", "mer kreativ – mest kreativ", "Hun vil være mer kreativ på jobben.", "她想在工作中更有创造力。", "🖍️"],
    ["tålmodig", "有耐心的；能等待或忍耐的", "形容词", "mer tålmodig – mest tålmodig", "Jeg skal være tålmodig og øve litt hver dag.", "我会耐心一些，每天练习一点。", "🧘"],
    ["kanskje", "也许；可能", "副词", "不变形", "Kanskje flytter jeg neste år.", "也许我明年会搬家。", "❔"],
    ["ofte", "经常", "副词", "比较级 oftere（更经常）", "Jeg skal besøke familien oftere.", "我会更经常去看家人。", "🔁"],
    ["mer", "更；更加；更多；（否定句中）不再/不……了", "副词", "mer", "Jeg vil lese mer.", "我想多读一些。", "➕"],
    ["neste", "下一个；接下来的（按时间或顺序）", "限定词/形容词", "neste", "Vi reiser neste sommer.", "我们明年夏天旅行。", "⏭️"],
    ["om fem år", "五年后（从现在起计算）", "时间短语", "om + 时间段 = ……之后", "Hvor bor du om fem år?", "五年后你住在哪里？", "⏳"],
    ["nær", "靠近；距离不远（nær + 地点）", "介词", "nær", "Marta vil bo nær fjell og natur.", "Marta 想住在靠近山和自然的地方。", "📍"],
    ["på", "在；到；关于（依搭配）", "介词", "固定搭配中学习", "Hun søker på en ny jobb.", "她在申请一份新工作。", "🧷"],
    ["til", "到；去；为了", "介词", "komme til å + V1", "Det kommer til å regne.", "这将会下雨。", "➡️"],
    ["med", "和；用；带着", "介词", "搭配决定具体意思", "Jeg skal reise med familien.", "我会和家人一起旅行。", "🤝"],
    ["om", "关于；（时间）……后/……时（依时间表达）", "介词", "om", "Vi snakker om framtida.", "我们在谈论未来。", "🕰️"]
  ].map(([word, zh, pos, forms, sentence, translation, scene]) => ({ word, zh, pos, forms, sentence, translation, scene })),
  // Short, source-checked Bokmålsordboka examples make key senses and collocations
  // visible in the rotating study context. Translations are editorial, not machine output.
  onlineExamples: {
    aktivitet: [{ no: "Hun er i aktivitet hele dagen.", zh: "她一整天都在活动。", note: "这里指持续处于活动状态；也可指一项具体活动，如 sosiale aktiviteter（社交活动）。", source: "https://ordbokene.no/bm/aktivitet" }],
    beslutning: [{ no: "Styret har fattet følgende beslutning.", zh: "董事会作出了以下决定。", note: "fatte en beslutning 是“作出决定”；ta en beslutning 也很常见。名词可用 en 或 ei，本专题采用 en。", source: "https://ordbokene.no/bm/beslutning" }],
    endring: [{ no: "Jeg foreslår noen få endringer.", zh: "我建议做几处小改动。", note: "endring 可指发生变化，也可指具体改动；本句是后者，常见结构 gjøre/foreslå endringer。", source: "https://ordbokene.no/bm/endring" }],
    fokusere: [{ no: "Vi må fokusere på å løse problemene.", zh: "我们必须把注意力集中在解决问题上。", note: "心理上的“专注”常用 fokusere på + 名词/动名词结构；å løse 在这里作介词 på 的补足语。", source: "https://ordbokene.no/bm/fokusere" }],
    forandre: [{ no: "Tidene forandrer seg.", zh: "时代在变化。", note: "forandre seg 表示“发生变化、变得不同”；与 forandre noe（改变某物）区分。", source: "https://ordbokene.no/bm/forandre%20seg" }],
    forbedre: [{ no: "Mye kan forbedres her.", zh: "这里有很多方面可以改进。", note: "forbedre + 对象表示“改善/提高某物”；被动形式 kan forbedres 表示“可以得到改进”。", source: "https://ordbokene.no/bm/forbedre" }],
    forbedring: [{ no: "Dette er en klar forbedring.", zh: "这是一个明显的改进。", note: "名词改善指相较之前变好；常说 en forbedring av noe（对某事的改进）。", source: "https://ordbokene.no/bm/forbedring" }],
    framtid: [{ no: "Framtiden ligger åpen foran deg.", zh: "你的未来有无限可能。", note: "framtid 不只表示时间上的“未来”，也可指一个人的前景；此句强调未来仍有多种可能。framtid 也可写作 fremtid。", source: "https://ordbokene.no/bm/framtid" }],
    glede: [{ no: "Hun sprer glede til alle rundt seg.", zh: "她把快乐带给身边的每一个人。", note: "这里的 glede 是“喜悦/快乐”这种感受；也可指令人高兴的事，如 en glede å møte familien。", source: "https://ordbokene.no/bm/glede" }],
    håp: [{ no: "Det er fortsatt håp om at han kan bli frisk.", zh: "他仍有康复的希望。", note: "håp om at … 表示“希望……/有望……”；håp 是中性名词：et håp – håpet。", source: "https://ordbokene.no/bm/h%C3%A5p" }],
    løsning: [{ no: "Vi må finne fram til en helhetlig løsning.", zh: "我们必须找到一个全面的解决方案。", note: "根据词典搭配 finne fram til en helhetlig løsning 补成完整句；问题语境中的 løsning 是答案或处理办法，化学语境中还可指溶液。名词可用 en 或 ei，本专题采用 en。", source: "https://ordbokene.no/bm/l%C3%B8sning" }],
    mer: [{ no: "Du må trene mer.", zh: "你得多锻炼一些。", note: "mer 修饰动作 trene，说明锻炼量需要增加；比较可数项目数量时通常用 flere。词典例句。", source: "https://ordbokene.no/bm/mer" }],
    oppnå: [{ no: "Hun oppnådde et godt resultat.", zh: "她取得了好成绩。", note: "oppnå + 结果/目标表示“达到、取得”；例如 oppnå enighet（达成一致）。", source: "https://ordbokene.no/bm/oppn%C3%A5" }],
    spare: [{ no: "Du sparer penger på å handle der.", zh: "在那儿购物能省钱。", note: "spare penger 既可指存钱，也可指省钱；本句因 på å handle der 表示“通过在那里购物省下钱”。", source: "https://ordbokene.no/bm/spare" }],
    forsett: [{ no: "Jeg har et urokkelig forsett.", zh: "我有一个坚定不移的决心。", note: "根据词典搭配 ha et urokkelig forsett 补成完整句。forsett 是“打算/意图”，而“新年计划”通常说 nyttårsforsett。", source: "https://ordbokene.no/bm/forsett" }],
    framgang: [{ no: "Framgangen fra i fjor er merkbar.", zh: "和去年相比，进步很明显。", note: "指朝更好方向发展的进步；Bokmål 也允许写 fremgang。", source: "https://ordbokene.no/bm/fremgang" }],
    fullføre: [{ no: "De fullfører et studium.", zh: "他们完成一项学业。", note: "根据词典搭配 fullføre et studium 补成完整句；fullføre 强调把课程、项目等做完/进行到底。", source: "https://ordbokene.no/bm/fullf%C3%B8re" }],
    "glede seg": [
      { no: "Jeg gleder meg til jul.", zh: "我很期待圣诞节。", note: "固定结构 glede seg til noe = 期待某事；代词随主语变化：jeg gleder meg、vi gleder oss。", source: "https://ordbokene.no/bm%2Cnn/glede%20seg%20til" },
      { no: "Jeg gleder meg over de fine høstfargene.", zh: "看到美丽的秋色，我感到很开心。", note: "glede seg over noe 表示因某事而高兴；注意它和表示“期待”的 glede seg til 不同。", source: "https://ordbokene.no/bm%2Cnn/glede%20seg" }
    ],
    innsats: [{ no: "Hun har gjort en stor innsats for norsk teater.", zh: "她为挪威戏剧事业作出了很大贡献。", note: "这里是“付出努力/作出贡献”；innsats 还可指比赛或彩票中的下注金额、器材中的可拆部件等，需依上下文区分。", source: "https://ordbokene.no/bm/innsats" }],
    karriere: [{ no: "Hun satser på en karriere som kunstner.", zh: "她立志以艺术家为职业发展方向。", note: "根据词典搭配 satse på en karriere som kunstner 补成完整句；此处指职业生涯，不是工作本身。", source: "https://ordbokene.no/bm%2Cnn/karriere" }],
    motivasjon: [{ no: "Mange mangler motivasjon for langvarig skolegang.", zh: "很多人缺乏长期求学的动力。", note: "词典原例为 mangle motivasjon for langvarig skolegang；本句补出主语。motivasjon 是做某事的意愿/动力，不等同于理由（grunn）。", source: "https://ordbokene.no/bm/motivasjon" }],
    nyttår: [{ no: "Han kommer over nyttår.", zh: "他过了新年就来。", note: "这里 over nyttår 指跨过新年之后；nyttår 也可指新年这个时点或岁末年初的一段时间。", source: "https://ordbokene.no/bm/nytt%C3%A5r" }],
    oppdage: [{ no: "Plutselig oppdaget han en mann fra hjemstedet.", zh: "他突然发现一个来自家乡的人。", note: "本句是“突然注意到/看见”；oppdage 也可指首次发现一个地方、现象或人才。", source: "https://ordbokene.no/bm/oppdage" }],
    opplevelse: [{ no: "Konserten ble en minneverdig opplevelse.", zh: "这场音乐会成了一段难忘的经历。", note: "指亲身经历的一件事或由此产生的体验；与表示技能、阅历的“经验”区分。名词可用 en 或 ei，本专题采用 en。", source: "https://ordbokene.no/bm/opplevelse" }],
    plan: [{ no: "Hvilke planer har du for framtiden?", zh: "你对未来有什么计划？", note: "plan 可指执行方案，也可指想法/打算；本句是未来打算。词典也收录 plan 的“平面/层面”同形词义，词性和搭配不同。", source: "https://ordbokene.no/bm/plan" }],
    prioritere: [{ no: "Denne saken bør prioriteres.", zh: "这件事应该优先处理。", note: "prioritere noe 是把某事排在其他事情之前；也可说 prioritere ønskene sine（排列自己的愿望优先级）。", source: "https://ordbokene.no/bm/46226" }],
    reise: [{ no: "Jeg drar på en reise til Paris.", zh: "我要去巴黎旅行。", note: "根据词典搭配 dra på en reise til Paris 补成完整句；名词可用 en 或 ei：en reise / ei reise。与动词 å reise（旅行、出发）分开记。", source: "https://ordbokene.no/bm/reise" }],
    energisk: [{ no: "Hun er et energisk menneske.", zh: "她是一个精力充沛、做事很有干劲的人。", note: "Bokmålsordboka 以 et energisk menneske 为例；这里补出主语和系动词，energisk 可描述精力旺盛、积极行动的人。", source: "https://ordbokene.no/bm/energisk" }],
    fokusert: [{ no: "Jeg vil være mer fokusert på norsk.", zh: "我想把更多注意力放在挪威语上。", note: "fokusert 是 fokusere 的过去分词作形容词；这里用 fokusert på 表示注意力集中在某事上。词典例句以 fokusere på 描述集中注意力。", source: "https://ordbokene.no/bm/fokusere" }],
    "komme til å": [{ no: "Hun kommer til å greie oppgaven.", zh: "她会完成这项任务。", note: "词典原例。komme til å + 动词原形可表示对未来的判断/预测；另有“碰巧、得以……”义，需看时态和语境。", source: "https://ordbokene.no/bm/komme%20til%20%C3%A5" }],
    kreativ: [{ no: "Hun er en kreativ kunstner.", zh: "她是一位有创意的艺术家。", note: "词典例句 en kreativ kunstner 扩成完整句；kreativ 不仅是“有想法”，还强调能产生并实现新点子。", source: "https://ordbokene.no/bm/kreativ" }],
    mer: [{ no: "Du må trene mer.", zh: "你得多锻炼。", note: "词典原例。mer 可表示数量增加（更多），也可修饰动作或形容词表示程度增加（更加）；本句修饰 trene。", source: "https://ordbokene.no/bm/mer" }],
    motivert: [{ no: "Hun er motivert for oppgaven.", zh: "她对这项任务很有动力。", note: "根据词典搭配 være motivert for oppgaven 补成完整句。常用 motivert for + 任务/活动，表达对做某事有意愿和动力。", source: "https://ordbokene.no/bm/%C3%A5%20motivere" }],
    neste: [{ no: "Toget stopper ikke på neste stasjon.", zh: "火车不会在下一站停车。", note: "词典原例。neste 表示顺序中紧接着的一个；neste uke/sommer 通常指接下来那一周/夏天。", source: "https://ordbokene.no/bm/neste" }],
    nær: [{ no: "Vi bor nær byen.", zh: "我们住在城附近。", note: "词典原搭配 bo nær byen 补成完整句。nær + 地点表示距离近；也可作形容词描述亲密关系，如 nære venner（亲密的朋友）。", source: "https://ordbokene.no/nno/bm/n%C3%A6r" }],
    om: [{ no: "Vi snakker om framtida.", zh: "我们在谈论未来。", note: "snakke om noe 是“谈论某事”；om 也出现在时间表达中，如 om en uke（一个星期后），不能只背成“关于”。", source: "https://ordbokene.no/nob/bm/42048" }],
    "om fem år": [{ no: "Om fem år bor jeg fortsatt i Norge.", zh: "五年后我仍住在挪威。", note: "按词典的时间搭配 om en uke（一个星期后）扩展成完整句；om + 时间段表示从现在起过……之后。", source: "https://ordbokene.no/nob/bm/42048" }],
    positiv: [{ no: "Hun har en positiv innstilling.", zh: "她抱着积极的态度。", note: "根据词典搭配 ha en positiv innstilling 补成完整句；positiv 可表示乐观/肯定，也可指有利的结果或检测呈阳性，须结合名词判断。", source: "https://ordbokene.no/bm/positiv" }],
    rolig: [{ no: "Sjøen var rolig.", zh: "海面很平静。", note: "词典原例。描述海面时是“平静”；描述一个人时可指镇定、从容，描述地点或声音时可指安静。", source: "https://ordbokene.no/bm/rolig" }],
    rutine: [{ no: "Hun hadde en fast rutine hver morgen.", zh: "她每天早上都有固定的习惯。", note: "词典原例。rutine 可指重复的日常习惯/办事程序，也可指通过练习获得的熟练经验；本句是日常习惯义。", source: "https://ordbokene.no/nob/bm/rutine" }],
    "se for seg": [{ no: "De ser for seg en sydhavsøy.", zh: "他们想象着一座南太平洋岛屿。", note: "词典原例，表示在脑中想象某个画面；短语中的反身代词随主语变化：jeg ser for meg、du ser for deg、de ser for seg。", source: "https://ordbokene.no/nob/bm/se%20for%20seg" }],
    skape: [{ no: "Vi vil skape noe nytt.", zh: "我们想创造一些新事物。", note: "根据词典搭配 skape noe nytt 补成完整句；skape 可指创造/形成，也可指造成某种结果，如 skape uro（引起不安）。", source: "https://ordbokene.no/nob/bm/skape" }],
    suksess: [{ no: "Boka ble en suksess.", zh: "这本书大获成功。", note: "词典原例。suksess 指事情取得了顺利、令人满意的结果；说某人成功可用 ha suksess。", source: "https://ordbokene.no/bm/suksess" }],
    sunn: [{ no: "Mosjon og rikelig med søvn er sunt.", zh: "锻炼和充足的睡眠有益健康。", note: "词典原例；此处是对健康有益。sunn 也可指明智（sunn skepsis，理性的怀疑）或稳健（sunn økonomi，稳健的经济状况）。", source: "https://ordbokene.no/bm/sunn" }],
    trene: [{ no: "Hun trener for å ta vare på kroppen.", zh: "她锻炼是为了保持身体健康。", note: "词典原例，trene 表示锻炼身体；也可说 trene noen（训练某人）或 trene et lag（执教一支队伍），宾语会改变含义。", source: "https://ordbokene.no/bm/TRENE" }],
    tålmodig: [{ no: "Han var tålmodig med barna.", zh: "他对孩子们很有耐心。", note: "词典原例。常用 tålmodig med noen 表示对某人有耐心，也可 tålmodig vente（耐心等待）。", source: "https://ordbokene.no/bm/t%C3%A5lmodig" }],
    utvikling: [{ no: "En ny metode er under utvikling.", zh: "一种新方法正在研发中。", note: "词典原例。under utvikling 表示正在开发/形成；utvikling 通常强调发展过程或进程，不一定意味着进步。名词可用 en 或 ei。", source: "https://ordbokene.no/bm/utvikling" }],
    valg: [{ no: "Jeg står foran et vanskelig valg.", zh: "我正面临一个艰难的选择。", note: "词典原例，表示必须在不同可能性中作选择；valg 也可指选举，如 kommunevalg（市镇选举）。", source: "https://ordbokene.no/bm/valg" }],
    vennskap: [{ no: "Det er godt vennskap mellom dem.", zh: "他们之间有着良好的友谊。", note: "词典原例。vennskap 指朋友之间的关系和相互善意；中性名词，常作为抽象关系使用。", source: "https://ordbokene.no/bm/vennskap" }]
  },
  dialogue: [
    ["Ingrid og Marta sitter på en kafé. De snakker om framtiden.", "Ingrid 和 Marta 坐在咖啡馆里。她们在谈论未来。"],
    ["– Jeg skal begynne på videreutdanning neste høst, sier Ingrid. Jeg vil bli spesialpedagog.", "“我明年秋天要开始继续进修，”Ingrid 说，“我想成为一名特殊教育教师。”"],
    ["– Det høres spennende ut, svarer Marta. Jeg kommer til å søke på jobb i et annet fylke. Kanskje flytter jeg.", "“听起来很令人兴奋，”Marta 回答，“我准备申请另一个郡的工作，也许我会搬家。”"],
    ["– Hvor da? spør Ingrid.", "“搬到哪里？”Ingrid 问。"],
    ["– Kanskje Troms eller Trøndelag. Jeg vil bo nær fjell og natur, sier Marta og smiler. Hva med deg?", "“也许去Troms或Trøndelag。我想住在靠近山和自然的地方，”Marta笑着说。“你呢？”"],
    ["– Jeg vil gjerne bo i Oslo, nær familien. Men jeg skal reise til Spania i sommer. Det blir deilig med sol.", "“我很想住在奥斯陆，离家人近一些。不过今年夏天我要去西班牙旅行。有阳光会很舒服。”"],
    ["De smiler. Begge drømmer om nye muligheter, men de er også litt spente på hva framtiden bringer.", "她们都笑了。两人都梦想着新的机会，同时也有点期待又紧张，不知道未来会带来什么。"]
  ],
  reading: [
    ["Emil sitter i stua med hunden Rex. Det er søndag kveld, og han har nettopp laget en kopp te. Han ser på kalenderen og tenker på det nye året som kommer.", "Emil 和狗狗 Rex 坐在客厅里。现在是星期天晚上，他刚泡好一杯茶。他看着日历，想着即将到来的新年。"],
    ["«Jeg skal gjøre noen endringer», sier han lavt. Han åpner datamaskinen og lager et dokument med tittelen «Mine mål for neste år». Først skriver han: «Jeg skal trene tre ganger i uka.»", "“我要做一些改变，”他轻声说。他打开电脑，建了一个名为《我的明年目标》的文档。首先写道：“我每周要锻炼三次。”"],
    ["Så legger han til: «Jeg vil spise sunnere og lage middag hjemme hver dag. Jeg kommer til å lage ukemenyer og handleliste hver søndag.»", "接着他补充：“我想吃得更健康，每天在家做晚饭。我会每周日制定一周菜单和购物清单。”"],
    ["Emil tar en pause og ser ut av vinduet. «Jeg skal bruke mindre tid på skjerm», sier han. «Jeg kommer til å lese flere bøker i stedet for å se på telefonen. Kanskje én bok i måneden.»", "Emil 停下来休息，看向窗外。“我要少花些时间看屏幕，”他说，“我会改为多读书，而不是一直看手机。也许每月读一本。”"],
    ["Han tenker også på økonomien. «Jeg vil spare penger. Jeg skal lage et budsjett og følge med på hva jeg bruker. Jeg kommer til å bruke en app for å holde oversikt.»", "他也考虑到财务。“我想存钱。我会做一份预算，并留意自己的支出。我会用一个应用来掌握收支。”"],
    ["Rex reiser seg og bjeffer lavt. Emil smiler. «Og vi skal gå tur hver dag. Det blir bra for helsa, både for meg og for deg, Rex.»", "Rex 站起来，低声叫了几下。Emil 笑了。“我们还要每天散步。这对我和你都有益健康，Rex。”"],
    ["Senere den kvelden ringer han lillebroren sin i Bergen. «Jeg planlegger et nytt og bedre år», sier Emil. «Jeg vil gjøre små endringer som gir stor forskjell.» Broren ler. «Det høres ut som du har en god plan. Jeg tror du kommer til å få det til.»", "那天晚些时候，他给在卑尔根的弟弟打电话。“我在计划一个崭新而更好的年份，”Emil 说，“我想做一些能带来大改变的小改变。”弟弟笑道：“听起来你的计划不错。我相信你会成功的。”"],
    ["«Ja», sier Emil og nikker. «Det blir et spennende år.»", "“是啊，”Emil 点点头，“这会是令人兴奋的一年。”"]
  ],
  goals: [
    "完成课程后，我能解释现在时、skal、kommer til å、vil 和 blir 的主要区别。",
    "我能使用未来表达谈论计划、愿望、预测和可能的结果。",
    "我能读懂 Ingrid 与 Marta 的对话和 Emil 的新年计划，并说出主要意思。",
    "我能在相关名词中识别 en/ei/et、定指和复数变化，并掌握常见形容词比较级。",
    "我能写一段关于自己未来目标的短文，并清楚标出哪些是计划、愿望和预测。"
  ],
  exercises: [
    { prompt: "Jeg ___ ei bok på søndag. （明确安排）", choices: ["leser", "skal leser", "vil leser", "blir lese"], answer: "leser", why: "有明确日程时间 på søndag，可用现在时表达已安排的未来；若强调个人计划，也可另说 Jeg skal lese ei bok på søndag。" },
    { prompt: "Jeg ___ rydde rommet i morgen. （已有计划）", choices: ["skal", "skal å", "kommer til", "blir"], answer: "skal", why: "已有计划用 skal + 动词原形；å 不放在 skal 和动作动词之间。" },
    { prompt: "Se på skyene! Det ___ regne. （根据迹象预测）", choices: ["kommer til å", "skal å", "vil å", "blir å"], answer: "kommer til å", why: "根据眼前迹象预测天气，使用 kommer til å + 原形：kommer til å regne。" },
    { prompt: "Jeg ___ lære å danse. （表达个人愿望）", choices: ["vil", "vil å", "blir", "kommer"], answer: "vil", why: "表达“我想学”用 vil + 动词原形。这里第二个 å 是 lære å danse 中的结构，不是接在 vil 后。" },
    { prompt: "I morgen ___ jeg besøke familien. （把时间放句首）", choices: ["skal", "jeg skal", "besøker jeg skal", "vil å"], answer: "skal", why: "主句遵循 V2：I morgen 是第一成分，变位动词 skal 必须第二位，然后才是主语 jeg。" },
    { prompt: "Hun drømmer ___ en ny jobb.", choices: ["om", "på", "til", "med"], answer: "om", why: "固定搭配 drømme om noe，表示“梦想某事”。" },
    { prompt: "Marta vil bo ___ fjell og natur.", choices: ["nær", "til", "på", "om"], answer: "nær", why: "nær 表示“靠近”，nær fjell og natur = 靠近山和自然。" },
    { prompt: "Jeg skal trene tre ganger ___ uka.", choices: ["i", "om", "til", "på"], answer: "i", why: "频率表达是 tre ganger i uka（每周三次）。" },
    { prompt: "frisk 的比较级和最高级是？", choices: ["friskere – friskest", "mer frisk – mest frisk", "frisker – friskeste", "friskere – friskeste"], answer: "friskere – friskest", why: "常见短形容词 frisk 使用 -ere/-est：frisk, friskere, friskest。" },
    { prompt: "god 的比较级和最高级是？", choices: ["bedre – best", "godere – godest", "mer god – mest god", "godest – bedre"], answer: "bedre – best", why: "god 是不规则变化：god – bedre – best。" },
    { prompt: "选出“一个目标”的正确形式。", choices: ["et mål", "en mål", "ei mål", "målene"], answer: "et mål", why: "mål 是中性名词，词典形式是 et mål；定指单数 målet，不定复数仍是 mål，定指复数 målene。" },
    { prompt: "“计划” en plan 的定指单数与不定复数是？", choices: ["planen – planer", "planet – planene", "plana – planas", "planen – planene"], answer: "planen – planer", why: "plan 是 en 名词：en plan → planen → planer → planene。题目问的是定指单数和不定复数。" },
    { prompt: "选择自然的表达：我想改善挪威语。", choices: ["Jeg vil forbedre norsken min.", "Jeg vil forbedrer norsken min.", "Jeg blir forbedre norsken min.", "Jeg kommer forbedre norsken min."], answer: "Jeg vil forbedre norsken min.", why: "vil 后接动词原形 forbedre，不加现在时词尾 -r，也不省掉 vil。" },
    { prompt: "选择自然的表达：我们明年会完成项目。", choices: ["Vi blir ferdige med prosjektet neste år.", "Vi blir ferdig prosjektet neste år.", "Vi vil ferdige med prosjektet.", "Vi kommer til blir ferdige."], answer: "Vi blir ferdige med prosjektet neste år.", why: "bli ferdig med noe 是“完成某事”；主语 vi 为复数，形容词 ferdig 配合变为 ferdige。" },
    { prompt: "Emil 将用什么方式少看手机？", choices: ["他会改为读更多书。", "他要每天买一本书。", "他会停止散步。", "他计划搬去 Bergen。"], answer: "他会改为读更多书。", why: "文中说：Jeg kommer til å lese flere bøker i stedet for å se på telefonen. 意思是他会用读更多书来代替看手机。" },
    { prompt: "根据对话，Ingrid 想成为什么？", choices: ["spesialpedagog", "lege", "lærer i Spania", "økonom"], answer: "spesialpedagog", why: "Ingrid 说：Jeg vil bli spesialpedagog. vil bli 表达她希望成为特殊教育教师。" }
  ],
  writingPrompts: [
    ["写至少三句，谈谈你在接下来一年想做、计划做或预计会做的事。", "分别尝试 vil、skal、kommer til å。课本中的2025已调整为适合当前时间的“接下来一年”。"],
    ["写一段短文，描述你认为十年后会做什么：你做什么工作？住在哪里？", "使用 om ti år，并把愿望与预测区分开。"],
    ["用未来表达说明你准备怎样庆祝下一个新年。", "至少使用 vil、skal、kommer til å 各一次。"],
    ["写五句关于你想在生活中改善的事情。", "使用 forbedre、endring、rutine 等主题词汇。"],
    ["列出几条新年计划，并同时使用 vil、skal 和 kommer til å。", "例如：Jeg vil trene mer. Jeg skal besøke familien min oftere. Jeg kommer til å lære noe nytt."],
    ["写一段短文，说说你认为明年会是什么样子：令人兴奋、困难，还是别的？", "使用 jeg tror … kommer til å … 或 det blir … 表达预测。"],
    ["写一小段，描述你认为家人新年会做什么。", "练习第三人称主语与 skal / vil / kommer til å。"],
    ["写一段关于你未来生活的短文：梦想的工作、想去的地方、让你快乐的事。", "尽量把不同未来表达和至少五个专题词汇连接成一段话。"]
  ]
};
