/* Scanned course handout Tema: fremtid, expanded into a self-study unit. */
window.FREMTID_TOPIC = {
  id: "fremtid", title: "Fremtid · 未来", level: "A2–B1", icon: "🚀",
  intro: "学会表达计划、意愿、预测和结果；把语法放进目标、家庭、工作与旅行的真实语境。",
  grammar: [
    { title: "现在时 + 未来时间", cue: "安排明确、时间表清楚", form: "现在时 + 未来时间词", example: "Jeg leser ei bok på søndag.", zh: "我星期天读一本书。", note: "挪威语常用现在时表达已经安排好的未来事项，特别是有明确时间词时。上下文必须能看出是未来。出行也常用现在时：Vi drar til Oslo neste uke（我们下周去奥斯陆）。" },
    { title: "skal · 计划与承诺", cue: "已有安排、决定或责任", form: "skal + 动词原形（不加 å）", example: "Jeg skal rydde rommet i morgen.", zh: "我明天要收拾房间。", note: "skal 强调说话人已有计划、安排或承诺。主语变化时 skal 不变，后面的动词保持原形：Vi skal besøke bestemor til helgen.（我们周末要去看奶奶。）" },
    { title: "kommer til å · 预测", cue: "根据迹象或判断预测结果", form: "kommer til å + 动词原形", example: "Det kommer til å regne i kveld.", zh: "今晚会下雨。", note: "常用于预测或认为某事很可能发生。注意结构中 til 后必须有 å：kommer til å regne。看到乌云时，这个表达尤其自然。" },
    { title: "vil · 愿望与意愿", cue: "想做、希望做、愿意做", form: "vil + 动词原形（不加 å）", example: "Jeg vil lære å danse.", zh: "我想学跳舞。", note: "vil 表达个人意愿、希望或选择；后面的动作仍用原形。lære å danse 中，å 属于 lære å danse 这个“学习做某事”的结构。" },
    { title: "blir · 结果与变化", cue: "描述未来会形成的状态或结果", form: "blir + 名词/形容词；或 blir + ferdig", example: "Det blir gøy å feire nyttår.", zh: "庆祝新年会很有趣。", note: "blir 是 bli 的现在时，可表示“将会变得/会是”。也可说 Vi blir ferdige med prosjektet neste uke（我们下周会完成项目）。单独的 blir 不等于英语 will + 动词原形。" },
    { title: "把五种表达放在一起比较", cue: "同一件事，不同语气", form: "时间表 / 计划 / 预测 / 愿望 / 结果", example: "Jeg lærer norsk neste år. / Jeg skal lære norsk. / Jeg kommer til å lære norsk. / Jeg vil lære norsk. / Det blir lettere.", zh: "我明年学挪威语。/ 我计划学挪威语。/ 我会学会挪威语（预测）。/ 我想学挪威语。/ 这会变得更容易。", note: "选择时先问自己：这是排好的日程吗？是我的计划吗？是预测吗？是愿望吗？还是在说结果/状态？不要把所有未来都机械地翻译成 will。" },
    { title: "主句 V2 语序", cue: "时间放句首时，变位动词仍在第二位", form: "I morgen + skal + jeg + rydde …", example: "I morgen skal jeg rydde rommet.", zh: "明天我会收拾房间。", note: "时间成分 I morgen 占主句第一位，变位动词 skal 必须紧跟其后，再放主语 jeg。不能说 I morgen jeg skal …。" },
    { title: "不规则动词与时态回顾", cue: "先找助动/情态动词，再看后面动词", form: "å ville–vil–ville–har villet · å skulle–skal–skulle–har skullet · å bli–blir–ble–har blitt", example: "Jeg vil spare mer. / Jeg sparte mer i fjor. / Jeg har spart mye.", zh: "我想多存钱。/ 去年我多存了钱。/ 我已经存了很多。", note: "情态动词 vil/skal 后用原形；过去的计划可用 skulle；描述已发生的过去用过去时；har 后要用完成分词。未来语境不等于每个动词都要加未来助动词。" }
  ],
  vocabulary: [
    ["et nyttår", "新年", "名词", "et nyttår – nyttåret – nyttår – nyttårene", "Vi skal feire nyttår med familien.", "我们要和家人一起庆祝新年。", "🎆"],
    ["et mål", "目标", "名词", "et mål – målet – mål – målene", "Målet mitt er å snakke bedre norsk.", "我的目标是把挪威语说得更好。", "🎯"],
    ["en drøm", "梦想", "名词", "en drøm – drømmen – drømmer – drømmene", "Drømmen hennes er å bo nær fjellet.", "她的梦想是住在山附近。", "💭"],
    ["en plan", "计划", "名词", "en plan – planen – planer – planene", "Vi har en plan for neste år.", "我们对明年有一个计划。", "🗓️"],
    ["en mulighet", "机会；可能性", "名词", "en mulighet – muligheten – muligheter – mulighetene", "Kanskje får jeg en ny mulighet på jobben.", "也许我会在工作中获得一个新机会。", "🚪"],
    ["en utfordring", "挑战", "名词", "en utfordring – utfordringen – utfordringer – utfordringene", "Det kan bli en spennende utfordring.", "这可能会成为一个令人兴奋的挑战。", "🧩"],
    ["en løsning", "解决办法", "名词", "en løsning – løsningen – løsninger – løsningene", "Vi skal finne en god løsning.", "我们会找到一个好办法。", "💡"],
    ["en suksess", "成功", "名词", "en suksess – suksessen – suksesser – suksessene", "Små steg kan føre til suksess.", "小小的进步也能带来成功。", "🏆"],
    ["ei helse", "健康", "名词", "ei helse – helsa", "Jeg skal gå tur for helsa.", "我打算散步来保持健康。", "💚"],
    ["ei trening", "锻炼；训练", "名词", "ei trening – treninga – treninger – treningene", "Jeg skal trene tre ganger i uka.", "我计划每周锻炼三次。", "🏃"],
    ["en endring", "改变", "名词", "en endring – endringen – endringer – endringene", "Jeg vil gjøre noen endringer.", "我想做一些改变。", "🔄"],
    ["en motivasjon", "动力", "名词", "en motivasjon – motivasjonen – motivasjoner – motivasjonene", "Familien gir meg motivasjon.", "家人给我动力。", "🔥"],
    ["en innsats", "努力；付出", "名词", "en innsats – innsatsen – innsatser – innsatsene", "Med jevn innsats lærer jeg mer.", "持续努力，我就能学得更多。", "💪"],
    ["en glede", "快乐；喜悦", "名词", "en glede – gleden – gleder – gledene", "Det blir en glede å møte familien.", "见到家人会是一件开心的事。", "😊"],
    ["en rutine", "日常习惯；固定程序", "名词", "en rutine – rutinen – rutiner – rutinene", "Jeg skal lage en ny rutine.", "我打算建立一个新的日常习惯。", "🔁"],
    ["et håp", "希望", "名词", "et håp – håpet – håp – håpene", "Jeg håper at det blir fint vær.", "我希望天气会很好。", "🌤️"],
    ["en utvikling", "发展；进步", "名词", "en utvikling – utviklingen – utviklinger – utviklingene", "Jeg ser en positiv utvikling.", "我看到了积极的进步。", "📈"],
    ["en beslutning", "决定", "名词", "en beslutning – beslutningen – beslutninger – beslutningene", "Hun skal ta en viktig beslutning.", "她要做一个重要决定。", "✅"],
    ["et forsett", "决心；新年计划", "名词", "et forsett – forsettet – forsetter – forsettene", "Nyttårsforsettet mitt er å lese mer.", "我的新年计划是多读书。", "📝"],
    ["en framtid", "未来", "名词", "en framtid – framtiden – framtider – framtidene", "Vi snakker om framtiden.", "我们在谈论未来。", "🔮"],
    ["en forbedring", "改善；进步", "名词", "en forbedring – forbedringen – forbedringer – forbedringene", "Jeg merker en forbedring i norsken min.", "我感觉自己的挪威语有了进步。", "📊"],
    ["en aktivitet", "活动", "名词", "en aktivitet – aktiviteten – aktiviteter – aktivitetene", "Vi skal velge en aktivitet for helgen.", "我们要为周末选一项活动。", "⚽"],
    ["et valg", "选择", "名词", "et valg – valget – valg – valgene", "Det er et viktig valg.", "这是一个重要的选择。", "🔀"],
    ["en opplevelse", "经历；体验", "名词", "en opplevelse – opplevelsen – opplevelser – opplevelsene", "Reisen blir en fin opplevelse.", "这次旅行会是一次美好的体验。", "🎡"],
    ["ei reise", "旅行；旅程", "名词", "ei reise – reisa – reiser – reisene", "Jeg skal planlegge ei reise.", "我打算计划一次旅行。", "🧳"],
    ["en karriere", "职业生涯", "名词", "en karriere – karrieren – karrierer – karrierene", "Hun vil starte en ny karriere.", "她想开启一段新的职业生涯。", "👩‍💻"],
    ["en familie", "家庭；家人", "名词", "en familie – familien – familier – familiene", "Jeg vil reise med familien.", "我想和家人一起旅行。", "👨‍👩‍👦"],
    ["et vennskap", "友谊", "名词", "et vennskap – vennskapet – vennskap – vennskapene", "Et godt vennskap betyr mye.", "一段美好的友谊很重要。", "🫶"],
    ["en framgang", "进展；进步", "名词", "en framgang – framgangen – framganger – framgangene", "Jeg har hatt god framgang.", "我进步很大。", "🌿"],
    ["å ville", "想；愿意", "动词", "vil – ville – har villet", "Jeg vil lære et nytt språk.", "我想学一门新语言。", "🗣️"],
    ["å skulle", "将要；计划；本应", "动词", "skal – skulle – har skullet", "Vi skal besøke familien i helgen.", "我们周末要去看家人。", "📌"],
    ["å komme til å", "将会；预计会", "动词结构", "kommer til å – kom til å – har kommet til å", "Det kommer til å regne i kveld.", "今晚会下雨。", "🌧️"],
    ["å bli", "变成；将会是", "动词", "blir – ble – har blitt", "Det blir lettere med øvelse.", "练习会让事情变得更容易。", "🌱"],
    ["å planlegge", "计划", "动词", "planlegger – planla – har planlagt", "Jeg planlegger en reise.", "我在计划一次旅行。", "🧭"],
    ["å håpe", "希望", "动词", "håper – håpet – har håpet", "Jeg håper å få mer tid.", "我希望能有更多时间。", "🤞"],
    ["å drømme", "做梦；梦想", "动词", "drømmer – drømte – har drømt", "Han drømmer om en ny jobb.", "他梦想着一份新工作。", "✨"],
    ["å forbedre", "改善；提高", "动词", "forbedrer – forbedret – har forbedret", "Jeg vil forbedre norsken min.", "我想提高自己的挪威语。", "⬆️"],
    ["å tenke", "想；思考", "动词", "tenker – tenkte – har tenkt", "Jeg tenker på framtida.", "我在思考未来。", "🤔"],
    ["å ønske", "希望；想要", "动词", "ønsker – ønsket – har ønsket", "Jeg ønsker meg en ny jobb.", "我希望找到一份新工作。", "🌠"],
    ["å starte", "开始；启动", "动词", "starter – startet – har startet", "Jeg skal starte et nytt prosjekt.", "我准备开始一个新项目。", "▶️"],
    ["å trene", "锻炼；训练", "动词", "trener – trente – har trent", "Jeg skal trene tre ganger i uka.", "我每周要锻炼三次。", "🏃‍♀️"],
    ["å lære", "学习；学会", "动词", "lærer – lærte – har lært", "Jeg vil lære et nytt språk.", "我想学一门新语言。", "📚"],
    ["å oppnå", "达到；实现", "动词", "oppnår – oppnådde – har oppnådd", "Jeg håper å oppnå målet mitt.", "我希望实现自己的目标。", "🏁"],
    ["å prøve", "尝试；努力", "动词", "prøver – prøvde – har prøvd", "Jeg skal prøve å spise sunnere.", "我会试着吃得更健康。", "🧪"],
    ["å spare", "存钱；节省", "动词", "sparer – sparte – har spart", "Jeg vil spare mer penger.", "我想多存一些钱。", "🐷"],
    ["å jobbe", "工作", "动词", "jobber – jobbet – har jobbet", "Jeg skal jobbe mindre neste år.", "我明年会少工作一些。", "💼"],
    ["å reise", "旅行；出行", "动词", "reiser – reiste – har reist", "Vi skal reise til et nytt land.", "我们要去一个新的国家旅行。", "✈️"],
    ["å spise", "吃", "动词", "spiser – spiste – har spist", "Jeg vil spise sunnere.", "我想吃得更健康。", "🥗"],
    ["å gjøre", "做；进行", "动词", "gjør – gjorde – har gjort", "Jeg skal gjøre noen endringer.", "我打算做一些改变。", "🛠️"],
    ["å fokusere", "专注；集中注意力", "动词", "fokuserer – fokuserte – har fokusert", "Jeg skal fokusere mer på norsk.", "我会更专注于挪威语。", "🔎"],
    ["å prioritere", "优先安排；优先考虑", "动词", "prioriterer – prioriterte – har prioritert", "Jeg vil prioritere helsa mi.", "我想把健康放在优先位置。", "📌"],
    ["å skape", "创造；营造", "动词", "skaper – skapte – har skapt", "Vi kan skape en god rutine.", "我们可以建立一个好习惯。", "🎨"],
    ["å forandre", "改变；使变化", "动词", "forandrer – forandret – har forandret", "Små steg kan forandre hverdagen.", "小小的进步可以改变日常生活。", "🦋"],
    ["å oppdage", "发现；察觉", "动词", "oppdager – oppdaget – har oppdaget", "Jeg kommer til å oppdage nye steder.", "我会发现一些新地方。", "🔭"],
    ["å glede seg", "期待；感到高兴", "动词短语", "gleder seg – gledet seg – har gledet seg", "Jeg gleder meg til reisen.", "我很期待这次旅行。", "🎉"],
    ["å fullføre", "完成；做完", "动词", "fullfører – fullførte – har fullført", "Jeg skal fullføre kurset.", "我准备完成这门课程。", "🏅"],
    ["å se for seg", "想象；设想", "动词短语", "ser for seg – så for seg – har sett for seg", "Jeg ser for meg en roligere hverdag.", "我想象一种更平静的日常生活。", "🪄"],
    ["frisk", "健康的；清新的", "形容词", "friskere – friskest", "Jeg vil bli friskere.", "我想变得更健康。", "🍃"],
    ["flink", "擅长的；能干的", "形容词", "flinkere – flinkest", "Hun blir flinkere til å snakke norsk.", "她会越来越擅长说挪威语。", "🌟"],
    ["god", "好的；擅长的", "形容词", "bedre – best（不规则）", "Det blir bedre neste år.", "明年会更好。", "👍"],
    ["sterk", "强壮的；强有力的", "形容词", "sterkere – sterkest", "Trening gjør kroppen sterkere.", "锻炼让身体更强壮。", "🏋️"],
    ["motivert", "有动力的", "形容词", "mer motivert – mest motivert", "Jeg føler meg mer motivert nå.", "我现在感觉更有动力了。", "⚡"],
    ["glad", "高兴的", "形容词", "gladere – gladest", "Barna blir glade når vi reiser.", "我们旅行时孩子们会很开心。", "😄"],
    ["aktiv", "积极的；活跃的", "形容词", "mer aktiv – mest aktiv", "Jeg skal være mer aktiv.", "我会更积极一些。", "🚴"],
    ["energisk", "精力充沛的", "形容词", "mer energisk – mest energisk", "En god rutine gjør meg mer energisk.", "良好的习惯让我更有精力。", "🔋"],
    ["fokusert", "专注的", "形容词", "mer fokusert – mest fokusert", "Jeg vil være mer fokusert på norsk.", "我想更专注于挪威语。", "🎧"],
    ["lykkelig", "幸福的", "形容词", "lykkeligere – lykkeligst", "Jeg blir lykkelig av tid med familien.", "和家人在一起让我幸福。", "🏡"],
    ["rolig", "平静的；安静的", "形容词", "roligere – roligst", "Det blir roligere etter ferien.", "假期后会安静一些。", "🌊"],
    ["sunn", "健康的", "形容词", "sunnere – sunnest", "Jeg vil spise sunnere.", "我想吃得更健康。", "🥦"],
    ["positiv", "积极的；正面的", "形容词", "mer positiv – mest positiv", "Jeg prøver å være mer positiv.", "我努力让自己更积极。", "☀️"],
    ["kreativ", "有创造力的", "形容词", "mer kreativ – mest kreativ", "Hun vil være mer kreativ på jobben.", "她想在工作中更有创造力。", "🖍️"],
    ["tålmodig", "有耐心的", "形容词", "mer tålmodig – mest tålmodig", "Jeg skal være tålmodig og øve litt hver dag.", "我会耐心一些，每天练习一点。", "🧘"],
    ["kanskje", "也许；可能", "副词", "不变形", "Kanskje flytter jeg neste år.", "也许我明年会搬家。", "❔"],
    ["ofte", "经常", "副词", "比较级 oftere（更经常）", "Jeg skal besøke familien oftere.", "我会更经常去看家人。", "🔁"],
    ["mer", "更多；更加", "副词", "mer", "Jeg vil lese mer.", "我想多读一些。", "➕"],
    ["neste", "下一个；接下来的", "限定词/形容词", "neste", "Vi reiser neste sommer.", "我们明年夏天旅行。", "⏭️"],
    ["om fem år", "五年后", "时间短语", "om + 时间段 = ……之后", "Hvor bor du om fem år?", "五年后你住在哪里？", "⏳"],
    ["nær", "靠近", "介词", "nær", "Marta vil bo nær fjell og natur.", "Marta 想住在靠近山和自然的地方。", "📍"],
    ["på", "在；到；关于（依搭配）", "介词", "固定搭配中学习", "Hun søker på en ny jobb.", "她在申请一份新工作。", "🧷"],
    ["til", "到；去；为了", "介词", "komme til å + V1", "Det kommer til å regne.", "这将会下雨。", "➡️"],
    ["med", "和；用；带着", "介词", "搭配决定具体意思", "Jeg skal reise med familien.", "我会和家人一起旅行。", "🤝"],
    ["om", "关于；在……后", "介词", "om", "Vi snakker om framtida.", "我们在谈论未来。", "🕰️"]
  ].map(([word, zh, pos, forms, sentence, translation, scene]) => ({ word, zh, pos, forms, sentence, translation, scene })),
  dialogue: [
    ["Ingrid og Marta sitter på en kafé. De snakker om framtiden.", "Ingrid 和 Marta 坐在咖啡馆里。她们在谈论未来。"],
    ["– Jeg skal begynne på videreutdanning neste høst, sier Ingrid. Jeg vil bli spesialpedagog.", "“我明年秋天要开始继续进修，”Ingrid 说，“我想成为一名特殊教育教师。”"],
    ["– Det høres spennende ut, svarer Marta. Jeg kommer til å søke på jobb i et annet fylke. Kanskje flytter jeg.", "“听起来很令人兴奋，”Marta 回答，“我准备申请另一个郡的工作，也许我会搬家。”"],
    ["– Hvor da? spør Ingrid.", "“搬到哪里？”Ingrid 问。"],
    ["– Kanskje Troms eller Trøndelag. Jeg vil bo nær fjell og natur, sier Marta og smiler. Hva med deg?", "“也许去Troms或Trøndelag。我想住在靠近山和自然的地方，”Marta笑着说。“你呢？”"],
    ["– Jeg vil gjerne bo i Oslo, nær familien. Men jeg skal reise til Spania i sommer. Det blir deilig med sol.", "“我很想住在奥斯陆，离家人近一些。不过今年夏天我要去西班牙旅行。有阳光会很舒服。”"],
    ["De smiler. Begge drømmer om nye muligheter, men de er også litt spente på hva framtiden bringer.", "她们都笑了。两人都梦想着新的机会，同时也有点期待又紧张，不知道未来会带来什么。"]
  ],
  reading: [
    ["Emil sitter i stua med hunden Rex. Det er søndag kveld, og han har nettopp laget en kopp te. Han ser på kalenderen og tenker på det nye året som kommer.", "Emil 和狗狗 Rex 坐在客厅里。现在是星期天晚上，他刚泡好一杯茶。他看着日历，想着即将到来的新年。"],
    ["«Jeg skal gjøre noen endringer», sier han lavt. Han åpner datamaskinen og lager et dokument med tittelen «Mine mål for neste år». Først skriver han: «Jeg skal trene tre ganger i uka.»", "“我要做一些改变，”他轻声说。他打开电脑，建了一个名为《我的明年目标》的文档。首先写道：“我每周要锻炼三次。”"],
    ["Så legger han til: «Jeg vil spise sunnere og lage middag hjemme hver dag. Jeg kommer til å lage ukemenyer og handleliste hver søndag.»", "接着他补充：“我想吃得更健康，每天在家做晚饭。我会每周日制定一周菜单和购物清单。”"],
    ["Emil tar en pause og ser ut av vinduet. «Jeg skal bruke mindre tid på skjerm», sier han. «Jeg kommer til å lese flere bøker i stedet for å se på telefonen. Kanskje én bok i måneden.»", "Emil 停下来休息，看向窗外。“我要少花些时间看屏幕，”他说，“我会改为多读书，而不是一直看手机。也许每月读一本。”"],
    ["Han tenker også på økonomien. «Jeg vil spare penger. Jeg skal lage et budsjett og følge med på hva jeg bruker. Jeg kommer til å bruke en app for å holde oversikt.»", "他也考虑到财务。“我想存钱。我会做一份预算，并留意自己的支出。我会用一个应用来掌握收支。”"],
    ["Rex reiser seg og bjeffer lavt. Emil smiler. «Og vi skal gå tur hver dag. Det blir bra for helsa, både for meg og for deg, Rex.»", "Rex 站起来，低声叫了几下。Emil 笑了。“我们还要每天散步。这对我和你都有益健康，Rex。”"],
    ["Senere den kvelden ringer han lillebroren sin i Bergen. «Jeg planlegger et nytt og bedre år», sier Emil. «Jeg vil gjøre små endringer som gir stor forskjell.» Broren ler. «Det høres ut som du har en god plan. Jeg tror du kommer til å få det til.»", "那天晚些时候，他给在卑尔根的弟弟打电话。“我在计划一个崭新而更好的年份，”Emil 说，“我想做一些能带来大改变的小改变。”弟弟笑道：“听起来你的计划不错。我相信你会成功的。”"],
    ["«Ja», sier Emil og nikker. «Det blir et spennende år.»", "“是啊，”Emil 点点头，“这会是令人兴奋的一年。”"]
  ],
  goals: [
    "完成课程后，我能解释现在时、skal、kommer til å、vil 和 blir 的主要区别。",
    "我能使用未来表达谈论计划、愿望、预测和可能的结果。",
    "我能读懂 Ingrid 与 Marta 的对话和 Emil 的新年计划，并说出主要意思。",
    "我能在相关名词中识别 en/ei/et、定指和复数变化，并掌握常见形容词比较级。",
    "我能写一段关于自己未来目标的短文，并清楚标出哪些是计划、愿望和预测。"
  ],
  exercises: [
    { prompt: "Jeg ___ ei bok på søndag. （明确安排）", choices: ["leser", "skal leser", "vil leser", "blir lese"], answer: "leser", why: "有明确日程时间 på søndag，可用现在时表达已安排的未来；若强调个人计划，也可另说 Jeg skal lese ei bok på søndag。" },
    { prompt: "Jeg ___ rydde rommet i morgen. （已有计划）", choices: ["skal", "skal å", "kommer til", "blir"], answer: "skal", why: "已有计划用 skal + 动词原形；å 不放在 skal 和动作动词之间。" },
    { prompt: "Se på skyene! Det ___ regne. （根据迹象预测）", choices: ["kommer til å", "skal å", "vil å", "blir å"], answer: "kommer til å", why: "根据眼前迹象预测天气，使用 kommer til å + 原形：kommer til å regne。" },
    { prompt: "Jeg ___ lære å danse. （表达个人愿望）", choices: ["vil", "vil å", "blir", "kommer"], answer: "vil", why: "表达“我想学”用 vil + 动词原形。这里第二个 å 是 lære å danse 中的结构，不是接在 vil 后。" },
    { prompt: "I morgen ___ jeg besøke familien. （把时间放句首）", choices: ["skal", "jeg skal", "besøker jeg skal", "vil å"], answer: "skal", why: "主句遵循 V2：I morgen 是第一成分，变位动词 skal 必须第二位，然后才是主语 jeg。" },
    { prompt: "Hun drømmer ___ en ny jobb.", choices: ["om", "på", "til", "med"], answer: "om", why: "固定搭配 drømme om noe，表示“梦想某事”。" },
    { prompt: "Marta vil bo ___ fjell og natur.", choices: ["nær", "til", "på", "om"], answer: "nær", why: "nær 表示“靠近”，nær fjell og natur = 靠近山和自然。" },
    { prompt: "Jeg skal trene tre ganger ___ uka.", choices: ["i", "om", "til", "på"], answer: "i", why: "频率表达是 tre ganger i uka（每周三次）。" },
    { prompt: "frisk 的比较级和最高级是？", choices: ["friskere – friskest", "mer frisk – mest frisk", "frisker – friskeste", "friskere – friskeste"], answer: "friskere – friskest", why: "常见短形容词 frisk 使用 -ere/-est：frisk, friskere, friskest。" },
    { prompt: "god 的比较级和最高级是？", choices: ["bedre – best", "godere – godest", "mer god – mest god", "godest – bedre"], answer: "bedre – best", why: "god 是不规则变化：god – bedre – best。" },
    { prompt: "选出“一个目标”的正确形式。", choices: ["et mål", "en mål", "ei mål", "målene"], answer: "et mål", why: "mål 是中性名词，词典形式是 et mål；定指单数 målet，不定复数仍是 mål，定指复数 målene。" },
    { prompt: "“计划” en plan 的定指单数与不定复数是？", choices: ["planen – planer", "planet – planene", "plana – planas", "planen – planene"], answer: "planen – planer", why: "plan 是 en 名词：en plan → planen → planer → planene。题目问的是定指单数和不定复数。" },
    { prompt: "选择自然的表达：我想改善挪威语。", choices: ["Jeg vil forbedre norsken min.", "Jeg vil forbedrer norsken min.", "Jeg blir forbedre norsken min.", "Jeg kommer forbedre norsken min."], answer: "Jeg vil forbedre norsken min.", why: "vil 后接动词原形 forbedre，不加现在时词尾 -r，也不省掉 vil。" },
    { prompt: "选择自然的表达：我们明年会完成项目。", choices: ["Vi blir ferdige med prosjektet neste år.", "Vi blir ferdig prosjektet neste år.", "Vi vil ferdige med prosjektet.", "Vi kommer til blir ferdige."], answer: "Vi blir ferdige med prosjektet neste år.", why: "bli ferdig med noe 是“完成某事”；主语 vi 为复数，形容词 ferdig 配合变为 ferdige。" },
    { prompt: "Emil 将用什么方式少看手机？", choices: ["他会改为读更多书。", "他要每天买一本书。", "他会停止散步。", "他计划搬去 Bergen。"], answer: "他会改为读更多书。", why: "文中说：Jeg kommer til å lese flere bøker i stedet for å se på telefonen. 意思是他会用读更多书来代替看手机。" },
    { prompt: "根据对话，Ingrid 想成为什么？", choices: ["spesialpedagog", "lege", "lærer i Spania", "økonom"], answer: "spesialpedagog", why: "Ingrid 说：Jeg vil bli spesialpedagog. vil bli 表达她希望成为特殊教育教师。" }
  ],
  writingPrompts: [
    ["写至少三句，谈谈你在接下来一年想做、计划做或预计会做的事。", "分别尝试 vil、skal、kommer til å。课本中的2025已调整为适合当前时间的“接下来一年”。"],
    ["写一段短文，描述你认为十年后会做什么：你做什么工作？住在哪里？", "使用 om ti år，并把愿望与预测区分开。"],
    ["用未来表达说明你准备怎样庆祝下一个新年。", "至少使用 vil、skal、kommer til å 各一次。"],
    ["写五句关于你想在生活中改善的事情。", "使用 forbedre、endring、rutine 等主题词汇。"],
    ["列出几条新年计划，并同时使用 vil、skal 和 kommer til å。", "例如：Jeg vil trene mer. Jeg skal besøke familien min oftere. Jeg kommer til å lære noe nytt."],
    ["写一段短文，说说你认为明年会是什么样子：令人兴奋、困难，还是别的？", "使用 jeg tror … kommer til å … 或 det blir … 表达预测。"],
    ["写一小段，描述你认为家人新年会做什么。", "练习第三人称主语与 skal / vil / kommer til å。"],
    ["写一段关于你未来生活的短文：梦想的工作、想去的地方、让你快乐的事。", "尽量把不同未来表达和至少五个专题词汇连接成一段话。"]
  ]
};
